export const employeesImportConfig = {
  headerRowIndex: 3,
  dataStartRowIndex: 5,
  table: 'employee_profiles',
  columns: [
    { field: 'full_name', label: 'Họ tên', required: true },
    { field: 'dob', label: 'Ngày sinh', type: 'date' },
    { field: 'gender', label: 'Giới tính', options: [['male', 'Nam'], ['female', 'Nữ'], ['other', 'Khác']] },
    { field: 'id_number', label: 'CCCD' },
    { field: 'id_issued_date', label: 'Ngày cấp CCCD', type: 'date' },
    { field: 'id_issued_place', label: 'Nơi cấp CCCD' },
    { field: 'permanent_address', label: 'Địa chỉ thường trú' },
    { field: 'current_address', label: 'Địa chỉ hiện tại' },
    { field: 'phone', label: 'SĐT' },
    { field: 'email', label: 'Email' },
    { field: 'marital_status', label: 'Tình trạng hôn nhân', options: [['single', 'Độc thân'], ['married', 'Đã kết hôn'], ['other', 'Khác']] },
    { field: 'department', label: 'Phòng ban', required: true },
    { field: 'position', label: 'Chức vụ', required: true },
    { field: 'join_date', label: 'Ngày vào làm', type: 'date', required: true },
    { field: 'status', label: 'Loại hợp đồng', options: [['probation', 'Thử việc'], ['active', 'HĐLĐ 1 năm'], ['active', 'HĐLĐ không xác định thời hạn']] },
    { field: 'basic_salary', label: 'Lương cơ bản', type: 'number' },
    { field: 'bank_name', label: 'Ngân hàng' },
    { field: 'bank_account', label: 'Số tài khoản' },
    { field: 'tax_code', label: 'Mã số thuế TNCN' },
    { field: 'insurance_code', label: 'Số sổ BHXH' },
    { field: 'education_level', label: 'Trình độ học vấn' },
    { field: 'major', label: 'Chuyên ngành' },
    { field: 'school', label: 'Trường' },
    { field: 'graduation_year', label: 'Năm tốt nghiệp', type: 'number' },
  ],
}
